### ISSUE TITLE
Add option for autostart with DesktopEnvironement btw.

### ISSUE THREAD

**Issue by dns2utf8** [rnestler/reboot-arch-btw#10]
So the user can enable it like this:

``` bash
kernel-updated --enable-kde
```

And maybe disable it again

**Comment by rnestler** [comment]
You can do that by just creating a appropriate .desktop file in `~/.config/autostart/`. See the [freedesktop specification](https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html).

**Comment by dbrgn** [comment]
In my opinion this should be done as part of packaging, not by the tool itself.

**Comment by rnestler** [comment]
Closing, since it should be done by packaging or the user.
