### ISSUE TITLE
Doesn't work with ck-generic-v3 kernel 

### ISSUE THREAD

**Issue by Sacro** [rnestler/reboot-arch-btw#136]
I'm using the `linux-ck-generic-v3` package and kernel

My `uname -r` gives me back `6.4.1-2-ck-generic-v3`

```sh
reboot-arch-btw 
Kernel
 installed: 6.4.1.arch2-1 (since 2 days ago)
 running:   6.4.1.2.ck.generic.v3
Reboot arch btw
```

Looks like it's comparing against the `linux` package, if that is removed I get `[2023-07-07T13:00:36Z ERROR reboot_arch_btw] Could not create kernel checker: Could not get version of installed kernel: could not find or read package`

**Comment by Sacro** [comment]
It's from http://repo-ck.com/

And in the wiki
https://wiki.archlinux.org/title/Unofficial_user_repositories/Repo-ck

I think it's just linux-ck with processor specific optimisations

**Comment by rnestler** [comment]
Ah I think it trips up because of the `v3` and that the variant has multiple `-`. The logic to figure out which parts of the `uname -r` output belong to the version and which to the variant is a bit tough, since the version can also contain alphanumeric stuff like `arch1` or `zen1` or whatever.
