### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by dbrgn** [rnestler/reboot-arch-btw#20]
I want to cargo-install this package :slightly_smiling_face:

**Comment by rnestler** [comment]
Hmm for that I need a better name I guess :slightly_smiling_face: or do you think the current one is OK?

**Comment by rnestler** [comment]
Yes, but it implies, that it only check for the kernel. Maybe arch-reboot-needed? Or just reboot-needed?

**Comment by dbrgn** [comment]
I nominate `i-reboot-arch-btw`

**Comment by rnestler** [comment]
Love it! See #22

**Comment by rnestler** [comment]
Published to https://crates.io/crates/reboot-arch-btw :slightly_smiling_face:
