### ISSUE TITLE
Support non default kernels btw.

### ISSUE THREAD

**Issue by rnestler** [rnestler/reboot-arch-btw#3]
Arch has more than one supported kernel (linux-lts for example). Currently kernel-updated checks only if the package linux got updated.

**Comment by rnestler** [comment]
If somebody who is running a non default kernel could share the output of `uname -a` it would help to fix this.

**Comment by CobaltSpace** [comment]
I use the zen kernel.
```
$ uname -a
Linux ROGArch 5.6.11-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 06 May 2020 17:32:39 +0000 x86_64 GNU/Linux
```

**Comment by rnestler** [comment]
So the version of `linux-zen` is: `extra/linux-zen 5.6.12.zen1-1` which means the uname output has an additional `-zen` post-fix.

**Comment by rnestler** [comment]
@CobaltSpace Could you test in #36 if it works on your system?

**Comment by CobaltSpace** [comment]
```
$ ./reboot-arch-btw
Kernel
 installed: 5.6.13.zen1-1 (since 1 days ago)
 running:   5.6.13-zen1-1
You should reboot arch btw!
Xorg server
 installed: 1.20.8-2 (since 11 days ago)
 running:   1.20.8
```

I have the `rust` package.
