### ISSUE TITLE
Watch for other critical parts of the system btw.

### ISSUE THREAD

**Issue by dns2utf8** [rnestler/reboot-arch-btw#5]
like
- [ ] libc
- [ ] glibc
- [ ] device-mapper
- [ ] cryptsetup
- [ ] lvm
- [ ] systemd
- [ ] dbus
- [ ] pulseaudio
- [ ] video drivers
- [ ] wayland
- [ ] x11 or maybe not, it will go away ...

**Comment by rnestler** [comment]
So for X11, video drivers a logout-login cycle would suffice won't it?

**Comment by dns2utf8** [comment]
maybe, when I had to use nvidia hardware with the closed source drivers it sometimes required a reboot.

**Comment by rnestler** [comment]
This is now possible generically :slightly_smiling_face:
