### ISSUE TITLE
Warn the user when not to reboot or suspend to disk btw.

### ISSUE THREAD

**Issue by dns2utf8** [rnestler/reboot-arch-btw#6]
Warn the user when packages like these change:

Reboot killer:
- [ ] grub

Suspend to disk killer:
- [ ] btrfs
- [ ] xfs / zfs
- [ ] mkinitcpio
- [ ] kmod
- [ ] linux

**Comment by rnestler** [comment]
Why shouldn't you reboot when grub changed?

**Comment by dbrgn** [comment]
Who uses grub anyways? :laughing:

**Comment by rnestler** [comment]
> Who uses grub anyways?

What do you use?

**Comment by dbrgn** [comment]
> What do you use?

[systemd-boot](https://wiki.archlinux.org/index.php/Systemd-boot) (part of systemd, previously called gummiboot, UEFI based)

**Comment by rnestler** [comment]
It's not clear to me what we should do here. If there is a reboot pending one probably shouldn't use suspend to disk.

**Comment by rnestler** [comment]
Closing. Feel free to reopen to discuss further.
