### ISSUE TITLE
Patch version "0" is broken btw.

### ISSUE THREAD

**Issue by dbrgn** [rnestler/reboot-arch-btw#8]
I just got this output:

```
installed: 4.7-1
running:   4.7.0-1
You should reboot your system!
```

Probably a bug, right?

**Comment by rnestler** [comment]
I'm not sure if it is a bug or if the package changed somehow. I will try to test it on my machine.

**Comment by rnestler** [comment]
It really seems to be a bug, since the package version really is 4.7 while the kernel reports 4.7.0. This means I need to parse the version numbers.

**Comment by rnestler** [comment]
I'm not sure if this is still broken. We probably need to wait for the next x.y.0 version of the kernel :wink:

**Comment by rnestler** [comment]
OK it is still a problem :laughing: 
```
Kernel
 installed: 5.16.arch1.1 (since 16 hours ago)
 running:   5.16.0.arch1.1
You should reboot arch btw!
```
