### ISSUE TITLE
Panic when running without linux package installed

### ISSUE THREAD

**Issue by emansom** [rnestler/reboot-arch-btw#97]
On my system I switched to `linux-zen` and removed `linux` using `pacman -Rdd linux`.

When running `reboot-arch-btw` it panics on not being able to get a version of the installed kernel.

```shell
ewout@x11sslf ~ % reboot-arch-btw
thread 'main' panicked at 'Could not get version of installed kernel', src/kernel.rs:52:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by rnestler** [comment]
Oh this is supposed to actually work. Can you post the output from `uname -r`?

**Comment by emansom** [comment]
> Oh this is supposed to actually work. Can you post the output from `uname -r`?
```shell
➜  ~ uname -r
6.0.10-zen2-1-zen
```

**Comment by emansom** [comment]
Works after reboot.

Seems to only happen when an alternate kernel is installed (_like `linux-zen`_), plus the normal kernel package `linux` removed while that still being the running kernel.

**Comment by rnestler** [comment]
> plus the normal kernel package linux removed while that still being the running kernel.

Ah that makes sense! We just figure out the running kernel (with uname) and then check the package version of that kernel. If the running kernel is uninstalled the query will fail.

It is quite the edge case, but it makes sense to handle the error anyways and just log it.
